CREATE TABLE `message` ( `ID` int(50) NOT NULL AUTO_INCREMENT COMMENT 'ID', `NICK_NAME` varchar(50) DEFAULT NULL COMMENT '昵称', `IP` varchar(50) DEFAULT NULL COMMENT 'IP', `INSERT_TIME` datetime DEFAULT NULL COMMENT '提交时间', PRIMARY KEY (`ID`) ) ENGINE=InnoDB AUTO_INCREMENT=51 DEFAULT CHARSET=utf8;


CREATE TABLE `user` ( `ID` int(50) NOT NULL AUTO_INCREMENT COMMENT 'ID', `NAME` varchar(50) DEFAULT NULL COMMENT '昵称', `password` varchar(50) DEFAULT NULL COMMENT 'password'  COMMENT '密码',  `salt` varchar(50) DEFAULT NULL COMMENT 'salt'  COMMENT '姓名', `INSERT_TIME` datetime DEFAULT NULL COMMENT '提交时间', PRIMARY KEY (`ID`) ) ENGINE=InnoDB AUTO_INCREMENT=51 DEFAULT CHARSET=utf8;
